{"name": "test_add[maxfail]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <testcase.test_calc.TestCalc object at 0x0000023BC1279AC0>, a = 9999999999, b = 9, expect = 99999999, get_calc = <test_code.calc.Calculator object at 0x0000023BC1308670>\ncaculate = None\n\n    @pytest.mark.parametrize(\"a,b,expect\", adddatas_data,\n                             ids=myid_add)\n    @pytest.mark.run(order=1)\n    def test_add(self, a, b, expect,get_calc,caculate):\n        # 实例化计算机类\n        # clac = Calculator()\n        if isinstance(a, str):\n            print(\"非数字类型\")\n            assert False\n    \n        elif a is None:\n            print(\"不能为空\")\n            assert False\n    \n        elif 999999 <= a or a <= -999999:\n            print(\"超出最大值\")\n>           assert False\nE           assert False\n\ntest_calc.py:64: AssertionError"}, "attachments": [{"name": "stdout", "source": "39425eb2-f886-4ad0-a701-5f129cbb9a9b-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "9999999999"}, {"name": "b", "value": "9"}, {"name": "expect", "value": "99999999"}], "start": 1612147341714, "stop": 1612147341714, "uuid": "4f2e204a-3715-43bf-bce4-80184bdeaa44", "historyId": "fe123e0c4c5bf5785fc63aa23eefa947", "testCaseId": "a7b29b08300809261dc069b49da8543b", "fullName": "test_calc.TestCalc#test_add", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "LAPTOP-CV4D84I5"}, {"name": "thread", "value": "32636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}